version: "3"
services:
  frontend:
    image: srnnnn/docker-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    depends_on:
      - mysql
    mem_limit: 128m

  nginx:
    restart: always
    image: srnnnn/docker-nginx
    ports:
      - "80:80"
    depends_on:
      - mysql

  backend:
    image: srnnnn/docker-backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_PORT
